# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=5, max_digits=11)),
                ('description', models.CharField(max_length=4040)),
                ('photo', models.CharField(max_length=1000)),
                ('amount', models.SmallIntegerField(max_length=5)),
                ('reviews', models.IntegerField(default=0, max_length=8)),
                ('rating', models.SmallIntegerField(default=0, max_length=2)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
