# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.SmallIntegerField(),
        ),
    ]
