# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
    ]
